0.1

diff --git a/jobs/redis/templates/bin/post-start.erb b/jobs/redis/templates/bin/post-start.erb
--- a/jobs/redis/templates/bin/post-start.erb
+++ b/jobs/redis/templates/bin/post-start.erb
@@ -5,7 +5,6 @@
   slave=link('redis_conn')
   if_link('slave_conn'){ |x| slave=x }
 %>
-result=0;
 
 <% if p('cluster_enabled').eql?('yes') %>
 REDIS_HOME="/var/vcap/packages/redis";
@@ -46,7 +45,7 @@ REDIS_INSTANCES="<%= instances %>";
 
 REDIS_SLAVE_PER_INSTANCE="";
 SLAVE_PER_INSTANCE=0;
-<% if_p('cluster_replicas_node_count') do |x| %>
+<% if_p('cluster_replicas_per_node') do |x| %>
 REDIS_SLAVE_PER_INSTANCE="--cluster-replicas <%= x %>";
 SLAVE_PER_INSTANCE=<%= x.to_i %>;
 <% end %>
@@ -67,9 +66,9 @@ AVAILABLE_NODES=0;
 for i in ${REDIS_ADDRESSES};
 do
   PING="$(${REDIS_CLI} -h ${i} -p ${REDIS_PORT} ${REDIS_PASSWORD} PING)";
-  if [[ -n "${PING}" ]] && [[ "${PING}" == "PONG" ]];
+  if [[ "${PING}" == "PONG" ]];
   then
-    ((AVAILABLE_NODES+=1));
+    ((AVAILABLE_NODES++));
   fi
 done
 
@@ -78,36 +77,46 @@ then
 <%
   if slave.instances.eql?(master.instances) %>
   ${REDIS_CLI} \
+    ${REDIS_PASSWORD} \
     --cluster create ${REDIS_MASTER_NODES} ${REDIS_SLAVE_NODES} \
-    ${REDIS_SLAVE_PER_INSTANCE} \
-    ${REDIS_PASSWORD} <<< "yes";
-  result=${?};
+    ${REDIS_SLAVE_PER_INSTANCE} <<< "yes";
+  exit ${?};
 <% else %>
+  if [[ ${REDIS_MASTER_INSTANCES} -gt ${REDIS_SLAVE_INSTANCES}/${SLAVE_PER_INSTANCE} ]];
+  then
+    echo "ERROR: Not enough slave: master\[${REDIS_MASTER_INSTANCES}\], slave\[${REDIS_SLAVE_INSTANCES}\], slave per master\[${SLAVE_PER_INSTANCE}\]" >&2;
+    exit 1;
+  fi
   ${REDIS_CLI} \
-    --cluster create ${REDIS_MASTER_NODES} \
-    ${REDIS_PASSWORD} <<< "yes";
-  REDIS_SLAVE_ARRAY=($(echo "${REDIS_SLAVE_ADDRESSES}"|tr ' ' '\n'));
-  k=0;
+    ${REDIS_PASSWORD} \
+    --cluster create ${REDIS_MASTER_NODES} <<< "yes";
+  if [[ ! ${?} -eq 0 ]];
+  then
+    exit ${?};
+  fi
   for i in ${REDIS_MASTER_ADDRESSES};
   do
     MASTER_ID="$(${REDIS_CLI} \
-      -h ${i} -p ${REDIS_PORT} ${REDIS_PASSWORD} \
+      ${REDIS_PASSWORD} \
+      -h ${i} -p ${REDIS_PORT} \
       CLUSTER MYID)";
     j=0;
-    while ${j} -lt ${SLAVE_PER_INSTANCE};
+    while [[ ${j} -lt ${SLAVE_PER_INSTANCE} ]];
     do
       ${REDIS_CLI} \
-        --cluster add-node ${REDIS_SLAVE_ARRAY[k]}:${REDIS_PORT} \
+        ${REDIS_PASSWORD} \
+        --cluster add-node ${REDIS_SLAVE_ADDRESSES%% *}:${REDIS_PORT} \
         ${i}:${REDIS_PORT} \
         --cluster-slave \
         --cluster-master-id ${MASTER_ID};
-      ((k+=1));
-      ((j+=1));
+      if [[ ! ${?} -eq 0 ]];
+      then
+        exit ${?};
+      fi
+      REDIS_SLAVE_ADDRESSES="${REDIS_SLAVE_ADDRESSES#* }";
+      ((j++));
     done
   done
 <% end %>
 fi
-
 <% end %>
-
-exit ${result};
