1.0.3

diff --git a/jobs/redis/templates/bin/post-deploy.erb b/jobs/redis/templates/bin/post-deploy.erb
--- a/jobs/redis/templates/bin/post-deploy.erb
+++ b/jobs/redis/templates/bin/post-deploy.erb
@@ -181,6 +181,8 @@ then
     echo "ERROR: All requested nodes are already in a cluster." >&2;
     exit 0;
   fi
+else
+  echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
 fi
 
 AVAILABLE_NODES=0;
@@ -332,7 +334,7 @@ then
         done
       done
     else
-      echo "ERROR: Redis CLUSTER NODES command failed." >&2;
+      echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
       exit ${ERR};
     fi
   done
@@ -383,7 +385,7 @@ then
       ERR=1;
     fi
   else
-    echo "ERROR: Redis CLUSTER NODES command failed." >&2;
+    echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
   fi
 fi
 <%- end -%>
diff --git a/jobs/redis_check/templates/bin/run.erb b/jobs/redis_check/templates/bin/run.erb
--- a/jobs/redis_check/templates/bin/run.erb
+++ b/jobs/redis_check/templates/bin/run.erb
@@ -234,7 +234,7 @@ then
     ERR=1;
   fi
 else
-  echo "ERROR: Redis CLUSTER NODES command failed: ${MSG}" >&2;
+  echo "ERROR: Redis CLUSTER NODES command failed: \"${MSG}\"." >&2;
   ERR=1;
 fi
 
@@ -289,13 +289,13 @@ then
           then
             echo "Update operation: succeed";
           else
-            echo "Update operation: failed: ${RESULT}";
+            echo "Update operation: failed: \"${RESULT}\".";
           fi
         else
-          echo "Append operation: failed: ${RESULT}";
+          echo "Append operation: failed: \"${RESULT}\".";
         fi
       else
-        echo "Read operation: failed: ${RESULT}";
+        echo "Read operation: failed: \"${RESULT}\".";
       fi
       RESULT="$("${CLI}" \
         ${CLI_OPTS} \
@@ -305,10 +305,10 @@ then
       then
         echo "Delete operation: succeed";
       else
-        echo "Delete operation: failed: ${RESULT}";
+        echo "Delete operation: failed: \"${RESULT}\".";
       fi
     else
-      echo "Create operation: failed: ${RESULT}";
+      echo "Create operation: failed: \"${RESULT}\".";
     fi
 <%- if master.p('replication') && !sentinel.nil? -%>
   done
